package com.movielabs.dcnc_cpl;

import java.util.*;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.stream.Stream;

/**
 * List of Studio codes, obtained from http://www.digitalcinemanamingconvention.com/appendix_5.asp
 * This file was generated by tablegen.pl
 */
public class Studio {

    private static Map<String, String> studios;
    private final static String fileName = "studio.txt";

    static {
        studios = new HashMap<String, String>();
        studios.put("01S", "01_STUDIO P.I.");
        studios.put("3DV", "DEEP VISION 3D");
        studios.put("ADS", "ALLIANCE DIGITAL STUDIOS");
        studios.put("AFG", "ARCHANGEL FILM GROUP");
        studios.put("AI", "ATOMIC IMAGING, CHICAGO");
        studios.put("ANIM", "ANIMASIA STUDIOS");
        studios.put("AS", "ASTRO SHAW");
        studios.put("ATF", "ASIA TROPICAL FILMS");
        studios.put("AVD", "AV-DESIGN");
        studios.put("BF", "BELARUSFILM");
        studios.put("BH", "BLUMHOUSE PRODUCTIONS");
        studios.put("BMG", "BUSCH MEDIA GROUP");
        studios.put("BRM", "BERRYMOUNT AUTOMATION");
        studios.put("BRW", "BREAKWATER STUDIOS");
        studios.put("BS", "BANTAM STREET");
        studios.put("CCC", "COLUMBIA COLLEGE CHICAGO");
        studios.put("CDC", "CDC UNITED NETWORK");
        studios.put("CF", "CHALIA FILMS");
        studios.put("CFSL", "CAFETICO FILMS");
        studios.put("CFV", "CONSTANTIN FILM VERLEIH");
        studios.put("CL", "CINEMALIVE");
        studios.put("CLS", "CINEMA LIBRE STUDIO");
        studios.put("CNRA", "CINERAMA");
        studios.put("CRO", "CROMOSOMA, S.A.");
        studios.put("DBDK", "DIGIBIO.DK");
        studios.put("DCK", "DCI KOMPETENZZENTRUM");
        studios.put("DEFI", "DELPHI FILMVERLEIH GMBH");
        studios.put("DFS", "DUALFILM, STUTTGART");
        studios.put("DI", "DISNEY");
        studios.put("DVF", "DUAL V FILMS");
        studios.put("EAG", "EAGLE PICTURES");
        studios.put("EDEL", "EDEL GERMANY GMBH");
        studios.put("ELA", "ELAMEDIA");
        studios.put("ELO", "ELO FILM SCHOOL HELSINKI");
        studios.put("EQF", "EQUINOXE FILMS");
        studios.put("EXC", "THE EXCHANGE");
        studios.put("FB", "FILM BILDER");
        studios.put("FF", "FOCUS FEATURES");
        studios.put("FG", "FEEL GOOD ENTERTAINMENT");
        studios.put("FIN", "FINAS PRODUCTIONS");
        studios.put("FRE", "FRENETIC FILMS");
        studios.put("FW", "FOCUS WORLD");
        studios.put("FX", "FOX SEARCHLIGHT");
        studios.put("FZ", "FRENZI FILMS");
        studios.put("GB", "GRAND BRILLIANCE");
        studios.put("GPI", "GOLAN STUDIOS, CHICAGO");
        studios.put("GR", "GRAMERCY PICTURES");
        studios.put("HF", "HEIMATFILM");
        studios.put("HFF", "HFF KONRAD WOLF");
        studios.put("HOOK", "STUDIO HOOK");
        studios.put("HSLU", "HOCHSCHULE LUZERN");
        studios.put("ICON", "ICON ENTERTAINMENT");
        studios.put("IFC", "IFC FILMS");
        studios.put("IFS", "IFS INTERNATIONALE FILMSCHULE KÖLN GMBH");
        studios.put("IMG", "IMAGINASTUDIO");
        studios.put("IMO", "INFINATE MOTION");
        studios.put("IND", "INDEPENDENT PICTURES");
        studios.put("IRP", "INFINITY ROAD PICTURES");
        studios.put("IRU", "IRUSOIN");
        studios.put("JAG", "JAGUAR FILMS PRODUCTIONS");
        studios.put("KCP", "KINO CYFROWE");
        studios.put("LA", "LOCAL ACQUISITION");
        studios.put("LFLM", "LUCAS FILMS");
        studios.put("LION", "LIONS GATE");
        studios.put("LOK", "LOOKNOW");
        studios.put("LOMO", "LOMOTION AG");
        studios.put("LSR", "LASERFILM CINE Y VÍDEO, SL");
        studios.put("LVT", "LVT");
        studios.put("MAX", "MAXIWORKS PRODUCTIONS");
        studios.put("MMG", "MOMOTION GMBH");
        studios.put("MMP", "MAGNA MANA PRODUCTION");
        studios.put("MOM", "MOMENTUM PICTURES");
        studios.put("MRMX", "MIRAMAX");
        studios.put("MRV", "MARVEL");
        studios.put("MSVP", "MYSTIC STUDIOS & VINAYAK PRODUCTIONS");
        studios.put("NT", "NEW LINE");
        studios.put("O2", "O2 FILMES");
        studios.put("OTA", "FOX ATOMIC");
        studios.put("OVSP", "OVERSPIL (DK)");
        studios.put("PAT", "PATHE DISTRIBUTION");
        studios.put("PC", "DREAMWORKS");
        studios.put("PC", "PARAMOUNT");
        studios.put("PC", "PARAMOUNT VANTAGE");
        studios.put("PEAK", "PEAK MEDIA");
        studios.put("PICH", "PICTUREHOUSE");
        studios.put("POLO", "POLO FILM (DK)");
        studios.put("PW", "PRIMEWORKS");
        studios.put("RAM", "RAM ENTERTAINMENT");
        studios.put("RED", "RED COMMUNICATIONS");
        studios.put("REL", "IM GLOBAL");
        studios.put("RF", "RAIN FILMS");
        studios.put("RLD", "REALD");
        studios.put("RP", "ROGUE PICTURES");
        studios.put("RSS", "RED SKY STUDIOS");
        studios.put("SA", "SCREEN ATTRACTIONS");
        studios.put("SAF", "SIERRA/AFFINITY");
        studios.put("SB", "SHOWBOX");
        studios.put("SBF", "SOAPBOX FILMS");
        studios.put("SKOP", "SKOP PRODUCTIONS");
        studios.put("SKT", "SKT INTERNATIONAL");
        studios.put("SM", "SUHAN MOVIES");
        studios.put("SPE", "SONY PICTURES ENTERTAINMENT");
        studios.put("STX", "STX ENTERTAINMENT");
        studios.put("SUM", "SUMMIT ENTERTAINMENT");
        studios.put("T25P", "TAKE 25 PICTURES");
        studios.put("TCF", "FOX");
        studios.put("TRIG", "TRIGON-FILM");
        studios.put("UIG", "UIGIG ENTERTAINMENT (SPAIN)");
        studios.put("UP", "UNIVERSAL");
        studios.put("UPI", "UNION PICTURES");
        studios.put("UTM", "U2 MEDIA");
        studios.put("VEX", "VIRTUAL EXPERIENCE");
        studios.put("WC", "DIMENSION");
        studios.put("WC", "WEINSTEIN CO.");
        studios.put("WR", "WARNER BROS.");
        studios.put("XM", "MGM");
        studios.put("ZHDK", "ZÜRCHER HOCHSCHULE DER KÜNSTE");
        studios.put("ZM", "ZOOM-ENTERTAINMENT");
    }

    public static String getLongName(String s) {
        return studios.get(s);
    }
}
